#!/bin/bash

RESULTS=$(vaccinate src/java/org/apache/cassandra/**/*.java | grep mean | sed -E 's/^[^:]+: (.+)/\1,/g' | tr -d '\n' | sed -E 's/^(.*),$/[\1]/g')

output=$(ove mkresult vaccinate cassandra)

cat > $output <<EOF
{
	"environment": {
		"uname": "$(uname -a)"
	},
	"results": $RESULTS
}
EOF

echo
echo "Results saved to $output."
echo
