#!/bin/bash

RESULTS=$(vaccinate src/java/org/apache/cassandra/**/*.java | grep mean | sed -E 's/^[^:]+: (.+)/\1,/g' | tr -d '\n' | sed -E 's/^(.*),$/[\1]/g')
UNIQUE=$(date +%Y-%m-%dT%H:%M:%S)

mkdir -p $OVE_BASE_DIR/results/cassandra
cat > $OVE_BASE_DIR/results/cassandra/vaccinate-$UNIQUE.json <<EOF
{
	"environment": {
		"uname": "$(uname -a)"
	},
	"results": $RESULTS
}
EOF

