#!/usr/bin/env python3

from tep.dashboard import Dashboard, Image, Component, Graph
from tep.results import *
import plotly.express as px
from pathlib import Path

import sys
import os
import json

def create_histogram(filename):
	with open(filename) as results_file:
		results = json.load(results_file)
		data = {"probe hits": results["results"]}
		return px.bar(data), results["meta"]


result_files = [(project, file) for project in get_projects() for file in get_results_files("dmce", project)]

dashboard = Dashboard(title = "DMCE")

for (project, file) in result_files:
	graph, meta = create_histogram(file)
	dashboard.add(Graph(graph, title=project, meta=meta))

if __name__ == "__main__":
	dashboard.build().serve()
