#!/usr/bin/env python3

from tep.dashboard import Dashboard
from tep.results import *
import tep_dashboard as tdc

import json
import plotly.express as px
from dash import dcc

def create_histogram(filename):
	with open(filename) as results_file:
		results = json.load(results_file)
		data = {"characters/line": results["results"]}
		return px.histogram(data), results["meta"]

result_files = [(project, file) for project in get_projects() for file in get_results_files("vaccinate", project)]

dashboard = Dashboard(title = "V.A.C.C.I.N.A.T.E.")

for (project, file) in result_files:
	figure, meta = create_histogram(file)
	dashboard.add(tdc.Widget(title=f"{project} (mean lines per file)", meta=meta, children=dcc.Graph(figure = figure)))

