#!/usr/bin/env bash

cd $OVE_BASE_DIR

if [ ! -d "${RESULT_DIR:?}" ]; then
	echo "error: no results found, run some tools?"
	exit 1
elif [ $# -eq 0 ]; then
	r=$(find "$RESULT_DIR" -maxdepth 1 -mindepth 1 -type d -exec basename {} \;)
	if [ "x$r" = "x" ]; then
		echo "error: no results found, run some tools?"
		exit 1
	fi
else
	r="$*"
fi

python3 ${OVE_OWEL_DIR:?}/dashboard/app.py $r
