#!/bin/bash

if [ $# -ne 1 ]; then
	echo "error: which project? choose one of:"
	printf "%s\n" $OVE_PROJECT_LIST
	exit 1
elif ! dir=$(ove-proj2path $1); then
	echo "error: can not get path for '$1'"
	exit
fi

cd ${dir}

output=$(ove mkresult depclean $1)
mvn se.kth.castor:depclean-maven-plugin:2.0.2-SNAPSHOT:depclean | tee /dev/stderr | $OVE_PROJECT_DIR/parsers/depclean/parse.py > $output

echo
echo "Results saved to $output."
echo

