#!/usr/bin/env bash

export OVE_LOCAL_ECHO=1

# build dashboard infra
ove buildme dashboard_components

# make sure we have vaccinate and DMCE
ove fetch vaccinate dmce

# build, install and setup DMCE
ove buildme dmce
ove dmce set-profile coverage

# instrument vaccinate with some DMCE probes
git -C $OVE_BASE_DIR/vaccinate checkout vaccinate.c
git -C $OVE_BASE_DIR/vaccinate clean -dfx
ove dmce launch -a -- vaccinate

# build vaccinate with instrumentation
ove buildme vaccinate

# run vaccinate on self
ove vaccinate vaccinate

# create dashboard results
ove dmce-histogram vaccinate

# start web server
ove dashboard dmce
