#!/usr/bin/python3

import os, sys
import numpy as np

user=os.getenv("LOGNAME")
dfile = "/tmp/" + user + "/dmce/dmcebuffer.bin"
data = np.fromfile(dfile, dtype=np.int32)
data = np.trim_zeros(data)
data = np.sqrt(data)
data = data.tolist()

print(data)
