#!/bin/bash

if [ "$OVE_BASE_DIR" == "" ]; then
		echo "Please run in an OVE environment."
		exit 1
fi

cd "$OVE_BASE_DIR"

NAME=ove-wara-container
CLEAN=0
docker inspect "$NAME" &> /dev/null || CLEAN=1
[ "$1" == "--clean" ] && CLEAN=1

cd "$OVE_BASE_DIR"

if [ $CLEAN == 1 ]; then
		echo "Starting clean environment..."
		docker rm -f "$NAME" 2> /dev/null
		$OVE_PROJECT_DIR/scripts/docker-image base --no-cache --build-arg UID --build-arg GID || exit 1
		docker run -ti --name="$NAME" -v="$PWD:/ove" wara-sw-ove
else
		echo "Reattaching..."
		docker start -ai "$NAME"
fi

