#!/usr/bin/env python3

import json
import sys
from tep import results

print(sys.argv)

if len(sys.argv) < 3:
    print("args error")
    #raise "TODO: print usage"

project = sys.argv[1]
tool = sys.argv[2]

tag = "default"
if len(sys.argv) > 3:
    tag = sys.argv[3]

meta = results.create_metadata(project, tool, tag)
path = results.get_result_path(meta)

output = json.load(sys.stdin)

with open(path, "w") as f:
    json.dump(results.create_results(meta, output), f)
    print()
    print(f"Results saved to: {path}")
    print()
