#!/usr/bin/env python3

import json
import sys
from tep import results

def load_output(path):
    with open(path, "r") as f:
        return json.load(f)

if len(sys.argv) < 3:
    print("Usage:")
    print(f"\t{sys.argv[0]} <project> <tool> [ <tag> [ output files ... ] ]")
    sys.exit(1)

project = sys.argv[1]
tool = sys.argv[2]

tag = "default"
if len(sys.argv) > 3:
    tag = sys.argv[3]

meta = results.create_metadata(project, tool, tag)

output_files = sys.argv[4:]
if len(output_files) == 0:
    output = json.load(sys.stdin)
else:
    output = dict([(path, load_output(path)) for path in output_files])

path = results.save_results(results.create_results(meta, output))

print()
print(f"Results saved to: {path}")
print()
