#!/bin/bash

dir=$(ove-proj2path $1)
files=$(find $dir -iregex '.*\.\(java\|c\|cc\|cpp\)')

vaccinate $files | grep mean | sed -E 's/^[^:]+: (.+)/\1,/g' | tr -d '\n' | sed -E 's/^(.*),$/[\1]/g' | ove-mkresult vaccinate $1

