#!/usr/bin/env bash

for p in wheel dash==2.1.0 plotly pandas pyyaml Werkzeug==2.0.0; do
	ove-echo cyan "install python package '$p'"
	if ! pip3 install --user --no-warn-script-location $p; then
		ove-echo error "'pip3 install --user $p' failed"
		exit 1
	fi
done

ove-echo cyan "npm install"
if ! npm install; then
	ove-echo error "'npm install' failed"
	exit 1
fi
