#!/usr/bin/env bash

if ! npm run build; then
	ove-echo error "'npm run build' failed"
	exit 1
elif ! python3 setup.py sdist bdist_wheel; then
	ove-echo error "'python3 setup.py sdist bdist_wheel' failed"
	exit 1
fi
